// zonas.js — mapeo de cada "local" de data.js (ALTAS_DATA) a su zona
// geográfica del AMBA, para el resumen "Altas por zona" del panel completo
// de Kevin en dashboard.html.
//
// Se clasifica por el PARTIDO/BARRIO al que pertenece cada local (según su
// nombre en la planilla fuente), no por geocoding de la dirección: eso evita
// el problema que tenía el mapa anterior, donde direcciones con nombre de
// calle común (San Martín, Rivadavia, Córdoba...) podían ubicarse en
// cualquier provincia del país. Acá el resultado es siempre correcto porque
// no depende de un servicio externo, solo del nombre del local.
//
// Zonas: CABA, Norte, Oeste y Sur cubren el AMBA (Área Metropolitana de
// Buenos Aires). "Otras" agrupa los pocos locales fuera del AMBA (Rosario,
// Mar del Plata y La Plata).
//
// Cómo actualizar: si aparece un local nuevo en data.js que no está en este
// mapeo, app.js lo suma dentro de "Otras" por defecto (no rompe el panel) —
// para clasificarlo bien, agregar la clave (el valor exacto del campo
// "local") a la zona que corresponda acá abajo.
window.ZONA_MAP = {
  // CABA
  "APER BARRACAS": "CABA",
  "APER CABALLITO 2": "CABA",
  "APER CALLAO": "CABA",
  "APER CONSTITUCION": "CABA",
  "APER CORRIENTES 4": "CABA",
  "APER FLORES 1": "CABA",
  "APER FLORES 2": "CABA",
  "APER MATADEROS": "CABA",
  "APER ONCE": "CABA",
  "APER PELLEGRINI": "CABA",
  "APER PUEYRREDON": "CABA",
  "APER PUEYRREDON 2": "CABA",
  "APER RETIRO": "CABA",
  "APER VILLA DEL PARQUE": "CABA",
  "BARRACAS": "CABA",
  "BELGRANO": "CABA",
  "BOEDO": "CABA",
  "CABALLITO 1": "CABA",
  "CABALLITO 2": "CABA",
  "CALLAO": "CABA",
  "CORRIENTES 1": "CABA",
  "CORRIENTES 2": "CABA",
  "CORRIENTES 3": "CABA",
  "CORRIENTES 4": "CABA",
  "ENTRE RIOS": "CABA",
  "FLORES 1": "CABA",
  "FLORES 2": "CABA",
  "FLORIDA": "CABA",
  "LAVALLE 1": "CABA",
  "LAVALLE 2": "CABA",
  "LEZAMA": "CABA",
  "LINIERS": "CABA",
  "LINIERS 1": "CABA",
  "LINIERS 2": "CABA",
  "LUGANO": "CABA",
  "Liniers 1": "CABA",
  "ONCE": "CABA",
  "PELLEGRINI": "CABA",
  "POMPEYA": "CABA",
  "PUEYRREDON": "CABA",
  "PUEYRREDON 1": "CABA",
  "PUEYRREDON 2": "CABA",
  "RETIRO": "CABA",
  "SAAVEDRA": "CABA",
  "SAN CRISTOBAL": "CABA",
  "SAN NICOLAS": "CABA",
  "SANTA FE": "CABA",
  "SAVEEDRA": "CABA",
  "TUCUMAN": "CABA",
  "URQUIZA": "CABA",
  "VILLA LUGANO": "CABA",
  // Norte
  "APER ADELINA": "Norte",
  "APER BALLESTER": "Norte",
  "APER DON TORCUATO": "Norte",
  "APER ESCOBAR 2": "Norte",
  "APER GARIN": "Norte",
  "APER JOSE LEON SUAREZ": "Norte",
  "APER MARTINEZ": "Norte",
  "APER OLIVOS": "Norte",
  "APER TALAR": "Norte",
  "APER VIRREYES": "Norte",
  "APER VTE. LOPEZ": "Norte",
  "BALLESTER 1": "Norte",
  "BALLESTER 2": "Norte",
  "BANAVIDEZ": "Norte",
  "BELLA VISTA": "Norte",
  "BENAVIDEZ": "Norte",
  "BOULOGNE": "Norte",
  "CHILAVERT": "Norte",
  "DEL VISO": "Norte",
  "DON TORCUATO": "Norte",
  "ESCOBAR": "Norte",
  "GARIN": "Norte",
  "GRAND BOURG": "Norte",
  "JOSE C. PAZ": "Norte",
  "JOSE C. PAZ 1": "Norte",
  "JOSE C. PAZ 2": "Norte",
  "JOSE LEON SUAREZ": "Norte",
  "LOMA HERMOSA": "Norte",
  "LOS POLVORINES": "Norte",
  "MANUEL ALBERTI": "Norte",
  "MAQUINISTA SAVIO": "Norte",
  "MASCHWITZ": "Norte",
  "MUNRO": "Norte",
  "OLIVOS": "Norte",
  "PACHECO": "Norte",
  "PACHECO 1": "Norte",
  "PACHECO 2": "Norte",
  "PACHECO 3": "Norte",
  "PILAR": "Norte",
  "PILAR 1": "Norte",
  "PILAR 2": "Norte",
  "PILAR2": "Norte",
  "PTE. SAAVEDRA": "Norte",
  "SAN FERNANDO": "Norte",
  "SAN ISIDRO": "Norte",
  "SAN ISIDRO 1": "Norte",
  "SAN ISIDRO 2": "Norte",
  "SAN MARTIN 1": "Norte",
  "SAN MARTIN 2": "Norte",
  "SAN MIGUEL 1": "Norte",
  "SAN MIGUEL 2": "Norte",
  "SAN MIGUEL 3": "Norte",
  "SAVIO": "Norte",
  "SOURDEAUX": "Norte",
  "TALAR": "Norte",
  "TIGRE": "Norte",
  "TORTUGUITAS": "Norte",
  "V. ADELINA": "Norte",
  "VIRREYES": "Norte",
  "VTE LOPEZ": "Norte",
  "W. MORRIS": "Norte",
  "ZARATE": "Norte",
  // Oeste
  "APER CIUDADELA": "Oeste",
  "APER GONZALEZ CATAN": "Oeste",
  "APER ITUZAINGO": "Oeste",
  "APER PALOMAR": "Oeste",
  "APER PASO DEL REY": "Oeste",
  "CASEROS": "Oeste",
  "CASEROS 1": "Oeste",
  "CASEROS 2": "Oeste",
  "CASTELAR": "Oeste",
  "CIUDADELA": "Oeste",
  "CRUCE CASTELAR": "Oeste",
  "EL PALOMAR": "Oeste",
  "GRAL RODRÍGUEZ": "Oeste",
  "HAEDO": "Oeste",
  "HAEDOO": "Oeste",
  "HURLINGHAM": "Oeste",
  "HURLINGHAM 1": "Oeste",
  "HURLINGHAM 2": "Oeste",
  "JAGUEL": "Oeste",
  "LAFERRERE": "Oeste",
  "LAFERRERE 1": "Oeste",
  "LAFERRERE 2": "Oeste",
  "LOMAS DEL MIRADOR": "Oeste",
  "LUJAN": "Oeste",
  "MERLO": "Oeste",
  "MERLO 1": "Oeste",
  "MERLO 2": "Oeste",
  "MERLO 3": "Oeste",
  "MORENO": "Oeste",
  "MORENO 1": "Oeste",
  "MORENO 2": "Oeste",
  "MORENO 3": "Oeste",
  "MORON": "Oeste",
  "MORON 1": "Oeste",
  "MORON 2": "Oeste",
  "MORON 3": "Oeste",
  "MORON 4": "Oeste",
  "MORON 5": "Oeste",
  "PADUA": "Oeste",
  "PALOMAR": "Oeste",
  "PASO DEL REY": "Oeste",
  "RAFAEL CASTILLO": "Oeste",
  "RAMOS MEJIA": "Oeste",
  "RAMOS MEJIA 1": "Oeste",
  "RAMOS MEJIA 2": "Oeste",
  "RAMOS MEJIA 3": "Oeste",
  "SAN JUSTO": "Oeste",
  "SAN JUSTO 1": "Oeste",
  "SAN JUSTO 2": "Oeste",
  "SAN JUSTO 3": "Oeste",
  "SANTOS LUGARES": "Oeste",
  "TAPIALES": "Oeste",
  // Sur
  "APER ADROGUE": "Sur",
  "APER BANFIELD": "Sur",
  "APER CROVARA": "Sur",
  "APER CRUCE VARELA": "Sur",
  "APER EZEIZA": "Sur",
  "APER GLEW": "Sur",
  "APER LOMAS": "Sur",
  "APER LOMAS 5": "Sur",
  "APER MONTE GRANDE 2": "Sur",
  "APER TEMPERLEY": "Sur",
  "APER VARELA 2": "Sur",
  "AVELLANEDA": "Sur",
  "BANFIELD": "Sur",
  "BERAZATEGUI 1": "Sur",
  "BERAZATEGUI 2": "Sur",
  "CLAYPOLE": "Sur",
  "CROVARA": "Sur",
  "CRUCE VARELA": "Sur",
  "E. ADROGUE": "Sur",
  "EZEIZA": "Sur",
  "GERLI": "Sur",
  "GLEW": "Sur",
  "LANUS": "Sur",
  "LANUS 1": "Sur",
  "LANUS 2": "Sur",
  "LANUS 3": "Sur",
  "LOMAS": "Sur",
  "LOMAS 1": "Sur",
  "LOMAS 2": "Sur",
  "LOMAS 3": "Sur",
  "LOMAS 4": "Sur",
  "LOMAS 5": "Sur",
  "MONTE GRANDE": "Sur",
  "MONTE GRANDE 1": "Sur",
  "MONTE GRANDE 2": "Sur",
  "QUILMES 1": "Sur",
  "QUILMES 2": "Sur",
  "QUILMES 3": "Sur",
  "SOLANO": "Sur",
  "TEMPERLEY 1": "Sur",
  "TEMPERLEY 2": "Sur",
  "TRISTAN SUAREZ": "Sur",
  "VARELA 1": "Sur",
  "WILDE": "Sur",
  // Otras
  "APER LA PLATA": "Otras",
  "APER MDQ 5": "Otras",
  "CITY BELL": "Otras",
  "LA PLATA": "Otras",
  "LA PLATA 1": "Otras",
  "LA PLATA 2": "Otras",
  "LA PLATA 3": "Otras",
  "LA PLATA 4": "Otras",
  "MDQ 1": "Otras",
  "MDQ 2": "Otras",
  "MDQ 3": "Otras",
  "MDQ 4": "Otras",
  "MDQ 5": "Otras",
  "ROSARIO": "Otras",
  "ROSARIO 1": "Otras",
  "ROSARIO 2": "Otras",
  "ROSARIO 3": "Otras",
};

window.ZONA_ORDER = ['CABA', 'Norte', 'Oeste', 'Sur'];
window.ZONA_LABELS = {
  CABA: 'CABA',
  Norte: 'Zona Norte',
  Oeste: 'Zona Oeste',
  Sur: 'Zona Sur',
  Otras: 'Otras provincias',
};
